[app]
http_enable = true
http_addr = "127.0.0.1:8080"

[db]
driver = "sqlite"
dsn = "./sqlite.db?_pragma=busy_timeout=10000&_pragma=journal_mode(WAL)"
max_idle_conns = 5
max_open_conns = 5
conn_max_lifetime = "1h"