@host = localhost:8080

### 登陆
# @name var
POST /api/users/login HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
  "username": "admin",
  "password": "admin"
}

### 获取规则列表
GET /api/rules HTTP/1.1
Content-Type: application/json
Host: {{host}}
Authorization: {{var.response.body.$.token}}

### 添加规则
POST /api/rules HTTP/1.1
Content-Type: application/json
Host: {{host}}
Authorization: {{var.response.body.$.token}}

{
  "source_port": 12345,
  "destination_port": 11111,
  "destination_address": "1.1.1.1",
  "remark": "这里是备注啊"
}

### 更新规则 /api/rules/:id
PUT /api/rules/1 HTTP/1.1
Content-Type: application/json
Host: {{host}}
Authorization: {{var.response.body.$.token}}

{
  "remark": "更新备注"
}

### 删除规则 /api/rules/:id
DELETE /api/rules/1 HTTP/1.1
Content-Type: application/json
Host: {{host}}
Authorization: {{var.response.body.$.token}}