@host = localhost:8080

### 登陆
# @name var
POST /api/users/login HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
  "username": "admin",
  "password": "admin"
}

### 注册
POST /api/users HTTP/1.1
Content-Type: application/json
Host: {{host}}

{
  "username": "admin",
  "password": "admin"
}

### 获取用户列表
GET /api/users HTTP/1.1
Content-Type: application/json
Host: {{host}}
Authorization: {{var.response.body.$.token}}

### 获取当前登陆用户详情
GET /api/user HTTP/1.1
Content-Type: application/json
Host: {{host}}
Authorization: {{var.response.body.$.token}}